### ISSUE TITLE
salt remote operation time out is too short

### ISSUE THREAD

**Issue by jschmid1** [oms4suse/sesceph#35]
On slower clusters the timeout value of 5 is too low.

`/usr/bin/ceph --connect-timeout 50 --keyring /var/lib/ceph/bootstrap-osd/ceph.keyring --name client.bootstrap-osd -f json-pretty status`
works,
while
`/usr/bin/ceph --connect-timeout 5 --keyring /var/lib/ceph/bootstrap-osd/ceph.keyring --name client.bootstrap-osd -f json-pretty status`

doesn't due to timeouts.

**Comment by oms4suse** [comment]
We have a PR https://github.com/oms4suse/sesceph/issues/35

**Comment by oms4suse** [comment]
Merged into master and released.
