### ISSUE TITLE
debug output of execute_local_command

### ISSUE THREAD

**Issue by hoonetorg** [oms4suse/sesceph#5]
For debugging issues with sesceph it would be nice to have more debugging output of what it does when calling salt with a higher debug level.

When f.e. calling 

```
salt-call -l all  sesceph.keyring_admin_create 
```

no debugging output of the called 
execute_local_command 
can be found in the debug output of salt.

execute_local_command at https://github.com/oms4suse/sesceph/blob/master/_modules/sesceph/utils.py#L22
calls
 **salt**['cmd.run_all']... with a loglevel 
and therefore some output of **salt**['cmd.run_all'] should be found in debugging output of salt with a loglevel equal or higher than trace.

Even changing the loglevel in 
https://github.com/oms4suse/sesceph/blob/master/_modules/sesceph/utils.py#L25
doesn't help.

Compared to the lvm module when calling 

```
salt-call -l debug lvm.lvcreate salttest vgceph size=1G
```

some lines of **salt**['cmd.run'] ... can be found in debugging output

```
[DEBUG   ] LazyLoaded cmd.run
[INFO    ] Executing command ['/usr/sbin/lvcreate', '-n', 'salttest', 'vgceph', '-L', '1G'] in directory '/root'
[ERROR   ] Command ['/usr/sbin/lvcreate', '-n', 'salttest', 'vgceph', '-L', '1G'] failed with return code: 5
[ERROR   ] output:   Logical volume "salttest" already exists in volume group "vgceph"
[INFO    ] Executing command ['lvdisplay', '-c', '/dev/vgceph/salttest'] in directory '/root'
[DEBUG   ] stdout:   /dev/vgceph/salttest:vgceph:3:1:-1:0:2097152:256:-1:0:-1:251:6
```

(see also https://github.com/saltstack/salt/blob/develop/salt/modules/linux_lvm.py#L341)

**Comment by hoonetorg** [comment]
I don't know what it has to do with, but probably the cause is, that 
salt['cmd.run_all'] 
is called nested (class, facet, class...)

**Comment by oms4suse** [comment]
Very good points :)
This should/will definitely be addressed.

**Comment by oms4suse** [comment]
@hoonetorg thank you for this issue I hope 

https://github.com/oms4suse/sesceph/commit/a5cc7d022237026e0914aeb69b98e4ae12b5cbab

goes some way to fixing the issue for you, and please note that I will be adding logging more and more.
